### ISSUE TITLE
Mark as Github Template Repository

### ISSUE THREAD

**Issue by darkmastermindz** [tomzorz/archetype#1]
Would it be possible to mark this repo as a GitHub [Template Repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)? 
\-\- thanks

**Comment by tomzorz** [comment]
I could make a separate repository as a template, but this one just has instructions on setting one up - it's not actually _a template_

**Comment by darkmastermindz** [comment]
Definitely would find that useful! @tomzorz
